
parameters:
  - name: k8sDir
    displayName: Kubernetes Scripts Dir Path
    type: string

  - name: Service
    displayName: Service Name
    type: string

  - name: azurekubernetes
    displayName: Azure kubernetes Service Connection Name
    type: string
    default: Azure Service Manage

  - name: cluster
    displayName: Azure kubernetes Cluster Name
    type: string

  - name: clusterResourceGroup
    displayName: Cluster Resource Group Name
    type: string

  - name: kubernetesScriptsFileNames
    type: object
    default: []

jobs:
  - job: Deploy${{ parameters.Service }}ToAks
    displayName: Deploy ${{ parameters.Service }} to AKS and Clean up

    steps:

      - task: KubectlInstaller@0
        displayName: Kubectl Installer

      - task: Kubernetes@1
        displayName: Setting up Kubeconfig
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: Azure Kubernetes Cluster
          command: login

      - ${{ each File in parameters.KubernetesScriptsFileNames }}:

          - task: Kubernetes@1
            displayName: kubectl deploy ${{ File }}
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: Azure Service Manage
              azureResourceGroup: servain-aks-rg-dev
              kubernetesCluster: servain-aks-dev
              command: apply
              arguments: -f ${{ parameters.k8sDir }}/${{ File }}

      - task: Kubernetes@1
        displayName: Cleaning up Kubeconfig
        condition: always()
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: '${{ variables.AKSServiceConnection }}'
          command: logout
