# trigger:
#   branches:
#     include:
#       - master

pool:
  vmImage: 'ubuntu-latest'


jobs:
    - job: TerraformValidateJob
      steps:
        - checkout: self
      
        - task: TerraformInstaller@0
          displayName: Terraform Install
          inputs:
            terraformVersion: 'latest'

        - task: TerraformCLI@0
          displayName: Terraform Init
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/k8s-app/terraform/pre'
            environmentServiceName: "Azure Service Manage"
            allowTelemetryCollection: false
            runAzLogin: true 

        - task: TerraformCLI@0
          displayName: Terraform validate
          inputs:
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/k8s-app/terraform/pre'
            environmentServiceName: "Azure Service Manage"
            allowTelemetryCollection: false
            runAzLogin: true 
          
        - task: TerraformCLI@0
          displayName: Terraform plan
          inputs:
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/k8s-app/terraform/pre'
            environmentServiceName: "Azure Service Manage"
            allowTelemetryCollection: false
            runAzLogin: true 
            commandOptions: '-out=$(Build.ArtifactStagingDirectory)/terraform.tfplan -detailed-exitcode'

        - bash: |
            env | sort
          displayName: 'output env var'

        - task: TerraformCLI@0
          displayName: 'terraform apply'
          condition: and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))
          inputs:
            command: apply
            environmentServiceName: 'Azure Service Manage'
            commandOptions: '$(System.ArtifactStagingDirectory)/terraform.tfplan'
