# trigger:
#   branches:
#     include:
#       - master

pool:
  vmImage: 'ubuntu-latest'


jobs:
    - job: TerraformValidateJob
      steps:
        - checkout: self
      
        - task: TerraformInstaller@0
          displayName: Terraform Install
          inputs:
            terraformVersion: 'latest'

        - task: TerraformCLI@0
          displayName: Terraform Init
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/k8s-app/terraform/pre'
            environmentServiceName: "Azure Service Manage"
            allowTelemetryCollection: false
            runAzLogin: true 